# Generated by Django 5.1.6 on 2025-02-23 18:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsComplete', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('TaskName', models.TextField()),
                ('TaskDescription', models.TextField(default='No Description')),
                ('TaskCategory', models.CharField(max_length=15)),
                ('Label', models.CharField(max_length=25)),
                ('DeadlineDate', models.DateField()),
                ('DeadlineTime', models.TimeField(default=datetime.time(23, 59))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
