# Generated by Django 5.1.6 on 2025-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_table',
            name='Label',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
